language: generic
sudo: required
services:
- docker
script:
- cd backend
- npm install
- npm test
- npm run test:e2e
- cd ..
after_success:
- docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
- heroku update
- heroku container:push web --app vantaa-black-panther
- heroku container:release web --app vantaa-black-panther
