version: '3.3'

services:

  backend:
    build: ./backend
    expose:
      - 5000
    environment:
      PORT: 5000
      DATABASE_HOST: postgres-dev-db
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - postgres-dev-db

  front-end:
    build: ./front-end
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./front-end/src:/front-end/src
      - ./front-end/public:/front-end/public
    links:
      - backend

  postgres-dev-db:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  admin:
    image: adminer
    ports:
      - 8080:8080