export const TOGGLE_FEED = 'TOGGLE_FEED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_NOTIFICATION_FILTER = 'SET_NOTIFICATION_FILTER';

export const NotificationFilters = {
    NEVER: 'NEVER',
    ALERTS_ONLY: 'ALERTS_ONLY',
    ALWAYS: 'ALWAYS',
};

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const SOURCES_FETCH_REQUEST = 'SOURCES_FETCH_REQUEST';
export const LOAD_SOURCES = 'LOAD_SOURCES';
export const SOURCES_FETCH_FAILED = 'SOURCES_FETCH_FAILED';
