export const TOGGLE_FEED = 'TOGGLE_FEED';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_NOTIFICATION_FILTER = 'SET_NOTIFICATION_FILTER';

export const NotificationFilters = {
    NEVER: 'NEVER',
    ALERTS_ONLY: 'ALERTS_ONLY',
    ALWAYS: 'ALWAYS',
};

export const FEED_FETCH_REQUEST = 'FEED_FETCH_REQUEST';
export const FEED_FETCH_SUCCESS = 'FEED_FETCH_SUCCESS';
export const FEED_FETCH_FAILED = 'FEED_FETCH_FAILED';
export const SOURCES_FETCH_REQUEST = 'SOURCES_FETCH_REQUEST';
export const SOURCES_FETCH_SUCCESS = 'SOURCES_FETCH_SUCCESS';
export const SOURCES_FETCH_FAILED = 'SOURCES_FETCH_FAILED';

export const FEED_ACTIVATED = 'FEED_ACTIVATED';
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION';
